export const PROFILE_IMAGE_IS_UPLOADING = 'profile/PROFILE_IMAGE_IS_UPLOADING';
export const CANCEL_SELECT_IMAGE = 'profile/CANCEL_SELECT_IMAGE';
export const IMAGE_PICKER_ERROR = 'profile/IMAGE_PICKER_ERROR';
