export const LOCAL_NOTIFICATION_PRESENTED = 'notifications/LOCAL_NOTIFICATION_PRESENTED';
export const LOCAL_NOTIFICATION_DATEPICKER_CHANGE = 'notifications/LOCAL_NOTIFICATION_DATEPICKER_CHANGE';
export const LOCAL_NOTIFICATION_SCHEDULED = 'notifications/LOCAL_NOTIFICATION_SCHEDULED';
