export const SIGN_OUT_SUCCESS = 'auth/SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'auth/SIGN_OUT_FAILURE';
export const SET_AUTH_TYPE = 'auth/SET_AUTH_TYPE';
export const SET_SIGNED_IN_USER = 'auth/SET_SIGNED_IN_USER';
export const SET_NAVIGATE_FROM_SPLASH = 'auth/SET_NAVIGATE_FROM_SPLASH';
export const TOGGLE_VERIFY_EMAIL_MODAL = 'auth/TOGGLE_VERIFY_EMAIL_MODAL';
export const RESET_PASSWORD_REQUEST = 'auth/RESET_PASSWORD_REQUEST';
