export const ON_GET_MAIL_ACCOUNT = 'mail/ON_GET_MAIL_ACCOUNT';
export const ON_CREATE_FOLDER_FOR_USER = 'mail/ON_CREATE_FOLDER_FOR_USER';
export const ON_GET_FOLDER_LISTS_FOR_USER = 'mail/ON_GET_FOLDER_LISTS_FOR_USER';
export const ON_CREATE_LIST = 'mail/ON_CREATE_LIST';
export const SET_ACTIVE_LIST = 'mail/SET_ACTIVE_LIST';
